name: Build

on:
  push:
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest
    strategy:
      matrix:
        with-sabi: [On, Off]
        python-version: ['3.13', 'pypy3.10']
      fail-fast: false
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5 
      with:
        python-version: ${{ matrix.python-version }}
    - name: Check CMake version
      shell: powershell
      run: cmake --version
    - name: Build
      shell: powershell
      run: cmake -S . -B build -D WITH_SABI=${{ matrix.with-sabi }}
